FROM postgres:13
USER root
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install wget -y && apt-get install unzip -y
RUN mkdir /data /data/database_dump /temp && chown -R postgres:postgres /data /temp
