# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Save UUID
    command: sh ./gitpod/save_uid.sh # runs during prebuild
    openMode: split-left

  - name: "Install Terraform"
    init: sh ./gitpod/install-terraform.sh
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - "Microsoft.Python"
    - "Microsoft.Pylance"
    - "Microsoft.Docker"
    - "GitKraken.GitLens (Insiders)"
    - "Microsoft.IntelliCode"
    - "4ops.Terraform"
