# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sh ./save_uid.sh # runs during prebuild
    command: echo 'start script'

  - name: "Install Terraform"
    init: sh ./gitpod/install-terraform.sh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - "Microsoft.Python"
    - "Microsoft.Pylance"
    - "Microsoft.Docker"
    - "GitKraken.GitLens (Insiders)"
    - "Microsoft.IntelliCode"
    - "4ops.Terraform"
